### ISSUE TITLE
关于原始数据集下载

### ISSUE THREAD

**Issue by heyuanpengpku** [iMoonLab/HGM2R#2]
hello，好像原始数据集的下载链接已经失效了，可否麻烦重新提供一下原始数据集呢？除此之外，相应的可视化代码可以从哪里获取呢？非常感谢！

**Comment by yifanfeng97** [comment]
您好，感谢您的关注，我们的服务器在维护，很快就能恢复。另外我会把数据额外备份到百度云盘，到时候更新到readme。

**Comment by heyuanpengpku** [comment]
好的，非常感谢您及时的回复！

**Comment by yifanfeng97** [comment]
链接已经回复，您看一下现在是否可以下载了。

**Comment by yifanfeng97** [comment]
可视化代码在我的另一个仓库：https://github.com/yifanfeng97/multi-modal-generation-for-shrec22

**Comment by heyuanpengpku** [comment]
好的好的，非常感谢！不知道可否加一个微信呢，可能有些问题还得请教哈哈
